---
title: "ProyectoTD2024 Grupo F"
author: "Maria Castellanos, Pablo Pons, Irene Gómez, Jenny Carolina Matamoros, Andreu Herrero"
date: "2024-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preguntas

1. A qué hora se suele ir más a comprar?
2. Cuál ha sido la evolución del precio de la leche?
3. Cuánta gente paga con tarjeta?
4. Cual es el precio medio de los tickets?
5. Media de la cantidad de "x producto" en los ultimos meses

```{r}
#Hacemos la importacion de los datos

#Primero vamos a guardar en una variable la ruta donde se encuentra la carpeta con todos nuestros ficheros
carpeta_ruta <- ".\\data"

#Ahora declararemos una variable donde usaremos el codigo list.files para obtener una lista de archivos dentro de la carpeta.
archivos_texto <- list.files(path = carpeta_ruta , pattern = "\\.txt$", full.names = TRUE)

# Crearemos un bucle el cual iterará sobre cada archivo en la lista creada previamente
for (archivo in archivos_texto) {
  # Hacer algo con cada archivo, por ejemplo, imprimir el nombre del archivo
  
  
  # Puedes agregar aquí el código para leer o procesar cada archivo según lo necesites
}

```

